name: yalla_notlop_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.3
dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  device_preview: ^1.3.1
  dashed_border: ^1.0.2
  flutter_bloc: ^8.1.6
  image_picker: ^1.2.2
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  uuid: ^4.5.3
  dartz: ^0.10.1
  go_router: ^17.3.0
  get_it: ^9.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-ExtraBold.ttf
          weight: 800
flutter_intl:
  enabled: true
